library(rgdal)
attendance <- read.csv("data-attendance.csv", stringsAsFactors=F)
yearly.attendance.bygym <- attendance %>% group_by(Year, gymid) %>% summarize(total = sum(attendance)) 
yearly.attendance.bygym <- left_join(yearly.attendance.bygym, gyms, by="gymid")

gyms <- read.csv("data-gymnasiums.csv", stringsAsFactors = FALSE)
data <- left_join(attendance, gyms, by="gymid")
bostonwards <- readOGR("Ward-Shapfiles/boston_wards_1915_1925.shp")
bostonwards <- spTransform(bostonwards, CRS("+proj=longlat +ellps=GRS80"))
privategyms <-  gyms %>% filter(type == "private")
